[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
regex = "1.11.1"
strum = { version = "0.26.3", features = ["derive"] }
